name: Workflow Secrets

on:                                   # evento de disparo trigger
  workflow_dispatch:                  # ativa o botao de disparo manual

jobs:
  show-secrets:
    runs-on: ubuntu-latest            # servidor publico do github
    steps:                            # steps a serem executados de forma sequencial estao abaixo
      - name: Checkout código         # nome do step
        uses: actions/checkout@v3     # comando a ser executado

      - name: Exibir variáveis
        run: |
          echo "Valor da VAR1: ${{ vars.VAR1 }}"
          echo "Valor da VAR2: ${{ vars.VAR2 }}"

      - name: Usar secret (valor mascarado)
        run: |
          echo "O secret está configurado: ${{ secrets.MEU_SECRET != '' }}"
          echo "Tentativa de exibir secret: ${{ secrets.MEU_SECRET }}"
